
class DP:
    MAX_ALERTS = 100
    MAX_LOGINS = 100
    MAX_TIMESTEPS = 100
    # MAX_TTC = 200
    MAX_TTC = 50
    SERVICE_REWARD = 1
    ATTACK_REWARD = -50
    EARLY_STOPPING_REWARD = -10


class ACTIONS:
    STOPPING_ACTION = 1